# Generated by Django 5.2.6 on 2025-09-20 20:21

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
